apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config-file
data:
  config.yaml: |
      model_list: 
        - model_name: gpt-4o
          litellm_params:
            model: azure/gpt-4o-ca
            api_base: https://litellm-test-instance.openai.azure.com/
            api_key: os.environ/CA_AZURE_OPENAI_API_KEY
      router_settings:
        redis_host: <your redis host>
        redis_password: <your redis password>
        redis_port: 1992