apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-deployment
  labels:
    app: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:main-stable
          args:
            - "--config"
            - "/app/proxy_server_config.yaml"
          ports:
          - containerPort: 4000
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
          - name: config-volume
            mountPath: /app/proxy_server_config.yaml
            subPath: config.yaml
          envFrom:
          - secretRef:
              name: litellm-secrets
          env:
            - name: AZURE_API_KEY
              value: "d6f****"
            - name: AZURE_API_BASE
              value: "https://openai"
            - name: LITELLM_MASTER_KEY
              value: "sk-1234"
            - name: DATABASE_URL
              value: "postgresql://ishaan*********"
      volumes:
        - name: config-volume
          configMap:
            name: litellm-config-file