apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: litellm-secrets
data:
  CA_AZURE_OPENAI_API_KEY: R0tqSFlDdTZLcUNpSk1JMmxiU3g3a0NmRTZIR3E3aEtTSFE2M1JEVVdjdnJIOHVBYkkzOEpRUUo5OUJHQUNZZUJqRlhKM3czQUFBQkFDT0dwMUl1Cg==